/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control;

/**
 *
 * @author Leonardo Sensiate
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Menu() {
        initComponents();
        jPmenu.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPmenu = new javax.swing.JPanel();
        jBjogar = new javax.swing.JButton();
        jLtitulo = new javax.swing.JLabel();
        jBcontinuar = new javax.swing.JButton();
        jBsair = new javax.swing.JButton();
        jPingame = new javax.swing.JPanel();
        jLingame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPmenu.setBackground(new java.awt.Color(0, 0, 0));

        jBjogar.setBackground(new java.awt.Color(255, 255, 0));
        jBjogar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jBjogar.setText("Jogar");
        jBjogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBjogarActionPerformed(evt);
            }
        });

        jLtitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLtitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLtitulo.setForeground(new java.awt.Color(255, 255, 0));
        jLtitulo.setText("PAC-MAN");

        jBcontinuar.setBackground(new java.awt.Color(255, 255, 0));
        jBcontinuar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jBcontinuar.setText("Continuar");

        jBsair.setBackground(new java.awt.Color(255, 255, 0));
        jBsair.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jBsair.setText("Sair");

        javax.swing.GroupLayout jPmenuLayout = new javax.swing.GroupLayout(jPmenu);
        jPmenu.setLayout(jPmenuLayout);
        jPmenuLayout.setHorizontalGroup(
            jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPmenuLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPmenuLayout.createSequentialGroup()
                        .addComponent(jLtitulo)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPmenuLayout.createSequentialGroup()
                        .addGroup(jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBcontinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBjogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBsair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(128, 128, 128))))
        );
        jPmenuLayout.setVerticalGroup(
            jPmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPmenuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLtitulo)
                .addGap(31, 31, 31)
                .addComponent(jBjogar)
                .addGap(18, 18, 18)
                .addComponent(jBcontinuar)
                .addGap(18, 18, 18)
                .addComponent(jBsair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPingame.setBackground(new java.awt.Color(0, 0, 0));

        jLingame.setBackground(new java.awt.Color(0, 0, 0));
        jLingame.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLingame.setForeground(new java.awt.Color(255, 255, 255));
        jLingame.setText("Jogo em andamento...");

        javax.swing.GroupLayout jPingameLayout = new javax.swing.GroupLayout(jPingame);
        jPingame.setLayout(jPingameLayout);
        jPingameLayout.setHorizontalGroup(
            jPingameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPingameLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLingame)
                .addGap(61, 61, 61))
        );
        jPingameLayout.setVerticalGroup(
            jPingameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPingameLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLingame)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPmenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPingame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPmenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPingame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBjogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBjogarActionPerformed

        GameScreen screen = new GameScreen();
        screen.setVisible(true);
        screen.createBufferStrategy(2);
        screen.go();
        jPmenu.setVisible(false);
        jPingame.setVisible(true);
    }//GEN-LAST:event_jBjogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcontinuar;
    private javax.swing.JButton jBjogar;
    private javax.swing.JButton jBsair;
    private javax.swing.JLabel jLingame;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPingame;
    private javax.swing.JPanel jPmenu;
    // End of variables declaration//GEN-END:variables
}
